INSERT INTO DEPARTEMENT (NDEP, NOMD) VALUES (SEQ_DEPARTEMENT.NEXTVAL, 'Informatique');
INSERT INTO DEPARTEMENT (NDEP, NOMD) VALUES (SEQ_DEPARTEMENT.NEXTVAL, 'Marketing');

INSERT INTO PERSONNE (PN, NOMP, PRENOM, EMAIL, DATEEMB, TITRE, ETATP, NDEP) VALUES
 (SEQ_PERSONNE.NEXTVAL, 'Dupont', 'Jean', 'jean.dupont@entreprise.com', TO_DATE('01/01/2022', 'DD/MM/YYYY'), 'Ingénieur', 'TRUE', 1);
INSERT INTO PERSONNE (PN, NOMP, PRENOM, EMAIL, DATEEMB, TITRE, ETATP, NDEP) VALUES 
 (SEQ_PERSONNE.NEXTVAL, 'Durand', 'Marie', 'marie.durand@entreprise.com', TO_DATE('01/02/2022', 'DD/MM/YYYY'), 'Assistant Marketing', 'TRUE', 2);

INSERT INTO PROJET (IDPROJ, NOMPROJ, DATEDEB, DESCRIPTION, PN, ETATPROJ) VALUES 
(SEQ_PROJET.NEXTVAL, 'Projet 1', TO_DATE('01/01/2023', 'DD/MM/YYYY'), 'Description Projet 1', 1, 'en cours de execution');
INSERT INTO PROJET (IDPROJ, NOMPROJ, DATEDEB, DESCRIPTION, PN, ETATPROJ) VALUES 
(SEQ_PROJET.NEXTVAL, 'Projet 2', TO_DATE('02/01/2023', 'DD/MM/YYYY'), 'Description Projet 2', 2, 'terminee');

INSERT INTO MATERIEL (ID_MAT, NOMM, TYPE, ETATD, ETATM, IDPROJ) VALUES 
(SEQ_MATERIEL.NEXTVAL, 'Ordinateur portable', 'Informatique', 'TRUE', 'FALSE', 1);
INSERT INTO MATERIEL (ID_MAT, NOMM, TYPE, ETATD, ETATM, IDPROJ) VALUES 
(SEQ_MATERIEL.NEXTVAL, 'Imprimante', 'Informatique', 'TRUE', 'TRUE', 1);
INSERT INTO MATERIEL (ID_MAT, NOMM, TYPE, ETATD, ETATM, IDPROJ) VALUES 
(SEQ_MATERIEL.NEXTVAL, 'Projecteur', 'Informatique', 'TRUE', 'TRUE', 2);

INSERT INTO AFFECTATIONPERSONNEL (PN, IDPROJ, DATEDEBUT, DATEFIN) VALUES 
(1, 1, TO_DATE('01/01/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'));
INSERT INTO AFFECTATIONPERSONNEL (PN, IDPROJ, DATEDEBUT, DATEFIN) VALUES 
(2, 2, TO_DATE('01/02/2023', 'DD/MM/YYYY'), TO_DATE('31/12/2023', 'DD/MM/YYYY'));

INSERT INTO TACHE (IDTACHE, DATE_ECHEANCE, DUREE_ESTIMEE, ETATT, DECRIPTION, IDPROJ, PN) VALUES 
(SEQ_TACHE.NEXTVAL, TO_DATE('01/06/2023', 'DD/MM/YYYY'), '4 mois', 'en cours de execution', 'Description Tâche 1', 1, 1);



/********************************* insersion par procedure *******************************************************/
