CREATE OR REPLACE PROCEDURE PROLONGER_TACHE(
    IDTACHE_IN IN NUMBER,
    NOUVELLE_DATE_ECHEANCE IN DATE
) IS
BEGIN
    UPDATE TACHE
    SET DATE_ECHEANCE = NOUVELLE_DATE_ECHEANCE
    WHERE IDTACHE = IDTACHE_IN;
END;
/
